name: CI
on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    runLint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run linter
              run: npm run lint

    runTypecheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run Typescript
              run: npm run tsc
