name: CI
on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    runLint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Environment
              uses: ./.github/actions/setupEnvironment
            - name: Run Eslint
              run: npm run lint

    runTypecheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Environment
              uses: ./.github/actions/setupEnvironment
            - name: Run Typescript
              run: npm run tsc

    runFormatter:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Environment
              uses: ./.github/actions/setupEnvironment
            - name: Run Prettier
              run: npm run check-format
